language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install fabric
  - fab build
  - pip install -r requirements.txt --upgrade
  - python setup.py install

after_install:
  - chmod +x tests/*.py

script: nosetests -vs tests